version: '3.4'

services:
  bored_bot:
    container_name: bored_bot
    build: ./bot
    env_file: .env.prod
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      HOSTNAME: https://www.s3bby.com/bored-bot
      HTTP_PORT: 5000
    restart: always

  bored_bot_legacy:
    container_name: bb_legacy
    build: ./bot_legacy
    env_file: .env.prod
    environment:
      NODE_ENV: production
    restart: always
