version: '3.8'

volumes:
  bored_bot_db_data:


services:
  mongo:
    image: mongo
    container_name: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27018:27017"
    volumes:
      - bored_bot_db_data:/data/db
