version: '2.0'

services:
  bored_bot:
    container_name: bored_bot
    build: .
    env_file: /etc/sjbha.s3bby.env
    environment:
      NODE_ENV: production
      HOSTNAME: https://sjbha.s3bby.com
      HTTP_PORT: 5000
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true