version: '2.0'

services:
  bored_bot:
    container_name: bored_bot
    build: .
    env_file: .env.prod
    environment:
      NODE_ENV: production
      HOSTNAME: https://www.s3bby.com/bored-bot
      HTTP_PORT: 5000
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true